### ISSUE TITLE
Arrow keys are not working in vscode terminal

### ISSUE THREAD

**Issue by rhzone** [vhqtvn/VHSCode-Android#10]
Up and down arrow key are not working as expected.

**Comment by vhqtvn** [comment]
It default to run sh which does not support history mode, try switching to bash by typing "bash" or change bash as default shell.

**Comment by rhzone** [comment]
> It default to run sh which does not support history mode, try switching to bash by typing "bash" or change bash as default shell.

How can I change default shell, both `chsh -s path_to_bash` and `Select Default Shell` don't work.

**Comment by vhqtvn** [comment]
please use the arrow key to navigate inside that popup list that allow you to select shell, for some reason vscode disable touch interaction for that widget that you cant select by touch, i'm thinking a way to overcome it.

**Comment by vhqtvn** [comment]
I implemented a fix for your problem, please wait until the updated version available on Google Play store. Thank you for reporting the problem!
