### ISSUE TITLE
building guide on README

### ISSUE THREAD

**Issue by usernein** [vhqtvn/VHSCode-Android#11]
Could you please add in README an small building guide?

I tried `./gradlew assembleRelease` but the result was an apk with 384MB (it used all the files under app/src/main/cpp)

I don't know how to build an apk for each arch

**Comment by vhqtvn** [comment]
You just need to keep your arch in abiFilters in this file:
https://github.com/vhqtvn/VHSCode-Android/blob/master/app/build.gradle

**Comment by usernein** [comment]
@vhqtvn ok, but how to build an apk for each arch?

**Comment by vhqtvn** [comment]
Hmm i dont know, i just build an aab and upload to appstore.
The easiest way is that you can make a script to update the target arch or just use the environment variable:

```
            abiFilters System.getenv('ABI_FILTER')
```

and then build 4 times:

```
ABI_FILTER=x86 ./gradlew assembleRelease
# do st with the built apk
ABI_FILTER=x86_64 ./gradlew assembleRelease
# do st with the built apk
....
```

Above code is untested but you should get the idea.

**Comment by vhqtvn** [comment]
Hi @usernein latest version now build each apk for each arch.
