### ISSUE TITLE
Disable autofill suggestions

### ISSUE THREAD

**Issue by davystrong** [vhqtvn/VHSCode-Android#13]
Hi, first of all, brilliant job developing this and making it free, I wanted this some time ago but didn't manage it myself, so thanks very much!
I was wondering if you have any way of disabling autofill suggestions when I type? I keep getting a name suggestion when I try to type which is most annoying because I'm using a hardware keyboard.
One other thing, since I was using a hardware keyboard I ticked the "hard keyboard" button, but when I try to type it always loses focus (so the cursor disappears after the first key press), however if I leave it unchecked it works perfectly. Am I misunderstanding what this button is for? I'm using my phone in desktop mode (Samsung Dex)

**Comment by vhqtvn** [comment]
I'll check on the autofill problem soon.
About the hw keyboard, it's mostly implemented for my blackberry device. Due to limitation of android IME which doesnt report the keycode but only 229 while composing word I used an hack that disable focus on the webview so that the IME never attach to textview and then forward all key events from activity to the browser to obtain correct keycode. I'll think a bit more to find alternal workaround.

**Comment by davystrong** [comment]
Thanks for the quick reply! No problem about the keyboard, maybe just specify the use case? Since the other mode works perfectly, it was just slightly confusing.

**Comment by vhqtvn** [comment]
Thank you, can you please take a screenshot so i can understand what's currently wrong?

**Comment by davystrong** [comment]
Turns out this issue doesn't occur near as frequently when "hard keyboard" is left unchecked. I could only get it to happen once, so it's no longer really an issue. I think the original problem was the view constantly regaining focus, then dismissing the suggestion lost the focus again. I've included a screenshot anyway but I think this issue can be closed.
![Screenshot_20200616-231417_VHSCode](https://user-images.githubusercontent.com/22416924/84847806-49b4fd80-b028-11ea-9b7e-91ee0669ebb3.jpg)

**Comment by vhqtvn** [comment]
Thank you from the screenshot that suggestion is from the browser, not from the keyboard, i think i can fix that using js, but seems that it's rarely to be able to replay. I'll close the issue for now but if I have any new idea i'll update.
