### ISSUE TITLE
Support other path

### ISSUE THREAD

**Issue by BlueWhaleYT** [vhqtvn/VHSCode-Android#3]
Hey there, currently my experience of using VHSCode is really great. I am satisfied for your work that allow mobile to operate VSCode. It is amusing.
However, it supports one path only that locates in the app files from storage/emulated/0/Android/data/vn.vhc.vhc/files.

I couldn't open a folder or a file that locate in other folders, for example in Download folder.

But overall it is marvelous.

**Comment by vhqtvn** [comment]
@BlueWhaleYT please check release 1.0.9, after update enable storage permission for the app (https://support.google.com/googleplay/answer/6270602?hl=en) and then restart the app.

**Comment by vhqtvn** [comment]
@BlueWhaleYT does it work for you?

**Comment by BlueWhaleYT** [comment]
yes thanks.

**Comment by vhqtvn** [comment]
Great, thank you for reporting!

**Comment by Jxck-S** [comment]
How do you select other folders I don't see the option anywhere?
