### ISSUE TITLE
Install apt packages

### ISSUE THREAD

**Issue by VickyBOSS** [vhqtvn/VHSCode-Android#4]
I can not install packages on terminal why ?

And how it is related to Termux

I want to install nodejs

**Comment by vhqtvn** [comment]
Termux use pkg command to install packages.

**Comment by vhqtvn** [comment]
@VickyBOSS do you have any more problem now?

**Comment by vhqtvn** [comment]
I installed nodejs package successfully
![86066ABE-E649-4FB0-9C46-D305E4DF7ED6](https://user-images.githubusercontent.com/8930337/83987556-d5fd5b80-a96a-11ea-8a9c-604430b999b7.jpeg)
`pkg install nodejs`
please keep the device awake while it’s installing, unpacking step might seem freeze but it doesnt, just wait dont kill it.

**Comment by vhqtvn** [comment]
If you have a corrupted prefix, try removing everything and try again `rm -rf /data/data/vn.vhn.vsc/files/*`, go back and reinstall server, and then start editor so that termux get installed.

**Comment by VickyBOSS** [comment]
![Screenshot_2020_0608_122958](https://user-images.githubusercontent.com/31494946/84001663-b8d58680-a984-11ea-8991-328dd746317a.png)

I tried this but extraction stuck at 37%

**Comment by vhqtvn** [comment]
It isnt stuck, just working.
I'll update in next version so that that step is more verbose.

**Comment by VickyBOSS** [comment]
Do.i need to inatall Termux App seperately

**Comment by vhqtvn** [comment]
No we cant access data in Termux and vice versa so i had to do some hacks to enable termus package installing.

**Comment by VickyBOSS** [comment]
Thank you
You are doing a nice job coz everyone can not afford a pc even in 2020 and there is no other app available on android for coding. Carry on

**Comment by VickyBOSS** [comment]
Have you published it on play store

**Comment by vhqtvn** [comment]
Hi not yet, i'll publish there soon.

**Comment by VickyBOSS** [comment]
Finally i succeeded in installing nodejs after stucking at 37% for almost 10 minutes
