### ISSUE TITLE
armv7l please

### ISSUE THREAD

**Issue by NoobSam777** [vhqtvn/VHSCode-Android#6]
Could make the application compatible with the armv7l?

**Comment by vhqtvn** [comment]
Ok i'll add support soon.

**Comment by vhqtvn** [comment]
Do you notice any error in the console on main screen?

**Comment by NoobSam777** [comment]
Screen

**Comment by vhqtvn** [comment]
Sorry are you missing attachment?

**Comment by NoobSam777** [comment]
did not understand

**Comment by vhqtvn** [comment]
You can enter the editor screen and it show the reconnect dialog after a while? After that please go back to main screen, scroll the console to bottom and take screenshot.

**Comment by NoobSam777** [comment]
![20200611_024224_rmscr](https://user-images.githubusercontent.com/49501697/84349365-8b0f5e00-ab8d-11ea-9f5a-b6ced3e5388e.jpg)
![20200611_024425_rmscr](https://user-images.githubusercontent.com/49501697/84349369-8c408b00-ab8d-11ea-98e8-8ae61979e7c8.jpg)
![20200611_024401_rmscr](https://user-images.githubusercontent.com/49501697/84349371-8d71b800-ab8d-11ea-9f73-cfde686d4a84.jpg)

**Comment by vhqtvn** [comment]
Ok i'll update the binary soon.

**Comment by vhqtvn** [comment]
@NoobSam777 please try this http://vhn.vn/android/vs-armv7-test-2.apk

**Comment by HitaloSama** [comment]
@vhqtvn I have an armeabi-v7a device and with this new build I received this error:

![](https://i.imgur.com/EqT8ORo.jpg)

**Comment by vhqtvn** [comment]
@HitaloSama Do you have Android developement tools installed? Please connect to device using adb shell by running
```
adb shell
```
after that use run-as to change to app's permission:
```
run-as vn.vhn.vsc
cd files
```
Now run `ls -la` to list files and try to run node by running `./node` and send me the output.

**Comment by vhqtvn** [comment]
@HitaloSama Oh i found the error building a new build

**Comment by HitaloSama** [comment]
> @HitaloSama Oh i found the error building a new build

Great, but if it's necessary, I can still do what you asked me to do.

**Comment by vhqtvn** [comment]
Please try the new build
http://vhn.vn/android/vs-armv7-test-3.apk

Please reset rootfs first (clicking on the cogs icon and tap reset rootfs).

**Comment by HitaloSama** [comment]
> Please try the new build
> http://vhn.vn/android/vs-armv7-test-3.apk
> 
> Please reset rootfs first (clicking on the cogs icon and tap reset rootfs).

I had the same error

**Comment by vhqtvn** [comment]
http://vhn.vn/android/vs-armv7-test-4.apk
@HitaloSama sorry this time it should work.

**Comment by NoobSam777** [comment]
There are times when I want to delete something and it won't go at all

**Comment by vhqtvn** [comment]
@NoobSam777 hm it still doesnt work?

**Comment by HitaloSama** [comment]
> http://vhn.vn/android/vs-armv7-test-4.apk
> @HitaloSama sorry this time it should work.

The error has been resolved and I am not having disconnected problem, so far everything seems to work as it should.

**Comment by HitaloSama** [comment]
An amazing job, congratulations for us providing something that until a day ago I found impossible on Android.

![](https://i.imgur.com/tjsZpN9.jpg)

**Comment by vhqtvn** [comment]
Thank you!

**Comment by NoobSam777** [comment]
> @NoobSam777 hm it still doesnt work?

 There is also the error that you cannot select the words in the code suggestion by clicking the enter button

**Comment by vhqtvn** [comment]
That error relating to codeserver port, but i'll try to fix it anw later.
This issue is now fixed.

**Comment by HitaloSama** [comment]
@vhqtvn I wanted to give a suggestion, could you add an option to maybe be able to decrease the size of the interface in the editor? Because even with my phone having a big screen it's still hard to use the editor.

**Comment by vhqtvn** [comment]
Thank you for your suggestion, I think i can do that, will try to add it soon.
