### ISSUE TITLE
git clone and other VS Code commands are not working

### ISSUE THREAD

**Issue by HitaloSama** [vhqtvn/VHSCode-Android#7]
**VS Code commands are receiving "permission denied" errors as in the image below:**

![](https://i.imgur.com/J8r3CuB.jpg)
![](https://i.imgur.com/oWR8EUw.jpg)

**Only these errors appear in VHSCode:**

![](https://i.imgur.com/XI7lmuc.jpg)

**Comment by vhqtvn** [comment]
To make it work i have to patch dpkg to replace all binary from com.termux to vn.vhn.vsc, seems that your setup somehow made my script doesnt work, please try to install using pkg (`pkg install git`) to see if it can work.

**Comment by HitaloSama** [comment]
@vhqtvn okay, I will try it.

**Comment by HitaloSama** [comment]
@vhqtvn the same error, I used apt remove git and then pkg install git.

![](https://i.imgur.com/UA9ojLM.jpg)

**Comment by vhqtvn** [comment]
Ok i'll check soon.

**Comment by vhqtvn** [comment]
@HitaloSama please check this version https://vhn.vn/android/app-fix-dpkg.apk
Please reset fs first.

**Comment by HitaloSama** [comment]
@vhqtvn worked now

**Comment by vhqtvn** [comment]
Great! I'm updating Play store version now.

**Comment by HitaloSama** [comment]
@vhqtvn Great, I'm waiting for the arrival of 1.1.04, here is only appearing 1.1.03 at Play Store... 🙂
