### ISSUE TITLE
CLang - which extension? 

### ISSUE THREAD

**Issue by anonimo82** [vhqtvn/VHSCode-Android#77]
Hello everyone.
Which extension should I install in order to use (already installed) clang compiler?

Thanks in advance for help.

@vhqtvn

**Comment by anonimo82** [comment]
By pressing ctrl+f6 or f6 on virtual keyboard (I use "Hacker's Keyboard") nothing happens. 
If I tap menu -> run -> run without debugging, it asks for a debugger extension.
What should I do?

**Comment by Xandor19** [comment]
Sorry, no idea, asi the C/C++ extension did not supported arm I gave up with C/C++, in the end, I keep my larger projects with the language at my desktop, I use this app for what I said earlier. You could try at settings, but I think it was with F5. Btw, I wasn't hable to install g++, how did you do?

**Comment by anonimo82** [comment]
I did nothing but installing Python, clang was a dependency and I found gcc and g++ installed aside
