### ISSUE TITLE
does not open android 10

### ISSUE THREAD

**Issue by Charlin-Lopes** [vhqtvn/VHSCode-Android#78]
im trying to install this updated version on my galaxy note 9 oni ui 2.0.  but displays and following message.  I don't know if samswng blocked
![Screenshot_20210827-192302_VHEditor](https://user-images.githubusercontent.com/22176481/131194514-b7b2b5e4-fa7c-4641-a538-885622eb2adb.jpg)

**Comment by sheng5498** [comment]
Try this
https://github.com/vhqtvn/VHEditor-Android/releases/download/v1.4.1/VHSCode-arm64.apk

**Comment by Xandor19** [comment]
Did you install from Google Play? You have to download the apk from the Releases of this repo and install manually

**Comment by Zeza93** [comment]
I got problem guys, app not installed on my samsung J6 2018 android 10

**Comment by Zeza93** [comment]
> https://github.com/vhqtvn/VHEditor-Android/releases/download/v1.4.1/VHSCode-arm64.apk

App not installed on my samsung j6 2018 android

**Comment by Aayushik129** [comment]
my android 10 not install this app please solve

**Comment by Kalmai221** [comment]
I am experiencing the same issue
